/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events. 

While this API is free to use it is subject to rate limiting for non-authenticated requests.

Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.

If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 * OpenAPI spec version: v2.2.0
 */
import axios,{
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery,
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey
} from 'react-query'
import type {
  PaginatedAgencyList,
  AgenciesListParams,
  AgencySerializerDetailed
} from '../../model'


/**
 * API endpoint that allows Agencies to be viewed.

GET:
Return a list of all the existing users.

MODE:
Normal and Detailed
/2.2.0/agencies/?mode=detailed

FILTERS:
Parameters - 'featured', 'agency_type', 'country_code'
Example - /2.2.0/agencies/?featured=true

SEARCH EXAMPLE:
/2.2.0/agencies/?search=nasa

ORDERING:
Fields - 'id', 'name', 'featured'
Example - /2.2.0/agencies/?ordering=featured
 */
export const agenciesList = (
    params?: AgenciesListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedAgencyList>> => {
    return axios.get(
      `/2.2.0/agencies/`,{
        params,
    ...options}
    );
  }


export const getAgenciesListQueryKey = (params?: AgenciesListParams,) => [`/2.2.0/agencies/`, ...(params ? [params]: [])];

    
export type AgenciesListQueryResult = NonNullable<Awaited<ReturnType<typeof agenciesList>>>
export type AgenciesListQueryError = AxiosError<unknown>

export const useAgenciesList = <TData = Awaited<ReturnType<typeof agenciesList>>, TError = AxiosError<unknown>>(
 params?: AgenciesListParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof agenciesList>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAgenciesListQueryKey(params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agenciesList>>> = ({ signal }) => agenciesList(params, { signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof agenciesList>>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}

/**
 * API endpoint that allows Agencies to be viewed.

GET:
Return a list of all the existing users.

MODE:
Normal and Detailed
/2.2.0/agencies/?mode=detailed

FILTERS:
Parameters - 'featured', 'agency_type', 'country_code'
Example - /2.2.0/agencies/?featured=true

SEARCH EXAMPLE:
/2.2.0/agencies/?search=nasa

ORDERING:
Fields - 'id', 'name', 'featured'
Example - /2.2.0/agencies/?ordering=featured
 */
export const agenciesRetrieve = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AgencySerializerDetailed>> => {
    return axios.get(
      `/2.2.0/agencies/${id}/`,options
    );
  }


export const getAgenciesRetrieveQueryKey = (id: number,) => [`/2.2.0/agencies/${id}/`];

    
export type AgenciesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof agenciesRetrieve>>>
export type AgenciesRetrieveQueryError = AxiosError<unknown>

export const useAgenciesRetrieve = <TData = Awaited<ReturnType<typeof agenciesRetrieve>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof agenciesRetrieve>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAgenciesRetrieveQueryKey(id);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof agenciesRetrieve>>> = ({ signal }) => agenciesRetrieve(id, { signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof agenciesRetrieve>>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

