/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agency,
    AgencyFromJSON,
    AgencyFromJSONTyped,
    AgencyToJSON,
} from './Agency';
import {
    AstronautStatus,
    AstronautStatusFromJSON,
    AstronautStatusFromJSONTyped,
    AstronautStatusToJSON,
} from './AstronautStatus';
import {
    AstronautType,
    AstronautTypeFromJSON,
    AstronautTypeFromJSONTyped,
    AstronautTypeToJSON,
} from './AstronautType';

/**
 * 
 * @export
 * @interface AstronautNormal
 */
export interface AstronautNormal {
    /**
     * 
     * @type {number}
     * @memberof AstronautNormal
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    name: string;
    /**
     * 
     * @type {AstronautStatus}
     * @memberof AstronautNormal
     */
    readonly status: AstronautStatus | null;
    /**
     * 
     * @type {AstronautType}
     * @memberof AstronautNormal
     */
    readonly type: AstronautType | null;
    /**
     * 
     * @type {Date}
     * @memberof AstronautNormal
     */
    dateOfBirth?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AstronautNormal
     */
    dateOfDeath?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    nationality: string;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    bio: string;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    twitter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    instagram?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    wiki?: string | null;
    /**
     * 
     * @type {Agency}
     * @memberof AstronautNormal
     */
    readonly agency: Agency | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    profileImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautNormal
     */
    readonly profileImageThumbnail: string;
    /**
     * 
     * @type {Date}
     * @memberof AstronautNormal
     */
    readonly lastFlight: Date;
    /**
     * 
     * @type {Date}
     * @memberof AstronautNormal
     */
    readonly firstFlight: Date;
}

export function AstronautNormalFromJSON(json: any): AstronautNormal {
    return AstronautNormalFromJSONTyped(json, false);
}

export function AstronautNormalFromJSONTyped(json: any, ignoreDiscriminator: boolean): AstronautNormal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'status': AstronautStatusFromJSON(json['status']),
        'type': AstronautTypeFromJSON(json['type']),
        'dateOfBirth': !exists(json, 'date_of_birth') ? undefined : (json['date_of_birth'] === null ? null : new Date(json['date_of_birth'])),
        'dateOfDeath': !exists(json, 'date_of_death') ? undefined : (json['date_of_death'] === null ? null : new Date(json['date_of_death'])),
        'nationality': json['nationality'],
        'bio': json['bio'],
        'twitter': !exists(json, 'twitter') ? undefined : json['twitter'],
        'instagram': !exists(json, 'instagram') ? undefined : json['instagram'],
        'wiki': !exists(json, 'wiki') ? undefined : json['wiki'],
        'agency': AgencyFromJSON(json['agency']),
        'profileImage': !exists(json, 'profile_image') ? undefined : json['profile_image'],
        'profileImageThumbnail': json['profile_image_thumbnail'],
        'lastFlight': (new Date(json['last_flight'])),
        'firstFlight': (new Date(json['first_flight'])),
    };
}

export function AstronautNormalToJSON(value?: AstronautNormal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'date_of_birth': value.dateOfBirth === undefined ? undefined : (value.dateOfBirth === null ? null : value.dateOfBirth.toISOString().substr(0,10)),
        'date_of_death': value.dateOfDeath === undefined ? undefined : (value.dateOfDeath === null ? null : value.dateOfDeath.toISOString().substr(0,10)),
        'nationality': value.nationality,
        'bio': value.bio,
        'twitter': value.twitter,
        'instagram': value.instagram,
        'wiki': value.wiki,
        'profile_image': value.profileImage,
    };
}

