/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AstronautDetailedSerializerNoFlights,
    AstronautDetailedSerializerNoFlightsFromJSON,
    AstronautDetailedSerializerNoFlightsFromJSONTyped,
    AstronautDetailedSerializerNoFlightsToJSON,
} from './AstronautDetailedSerializerNoFlights';
import {
    AstronautRole,
    AstronautRoleFromJSON,
    AstronautRoleFromJSONTyped,
    AstronautRoleToJSON,
} from './AstronautRole';

/**
 * 
 * @export
 * @interface AstronautFlight
 */
export interface AstronautFlight {
    /**
     * 
     * @type {number}
     * @memberof AstronautFlight
     */
    readonly id: number;
    /**
     * 
     * @type {AstronautRole}
     * @memberof AstronautFlight
     */
    readonly role: AstronautRole | null;
    /**
     * 
     * @type {AstronautDetailedSerializerNoFlights}
     * @memberof AstronautFlight
     */
    readonly astronaut: AstronautDetailedSerializerNoFlights | null;
}

export function AstronautFlightFromJSON(json: any): AstronautFlight {
    return AstronautFlightFromJSONTyped(json, false);
}

export function AstronautFlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): AstronautFlight {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': AstronautRoleFromJSON(json['role']),
        'astronaut': AstronautDetailedSerializerNoFlightsFromJSON(json['astronaut']),
    };
}

export function AstronautFlightToJSON(value?: AstronautFlight | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

