/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DockingLocation,
    DockingLocationFromJSON,
    DockingLocationFromJSONTyped,
    DockingLocationToJSON,
} from './DockingLocation';
import {
    SpacecraftFlightSerializerForDockingEvent,
    SpacecraftFlightSerializerForDockingEventFromJSON,
    SpacecraftFlightSerializerForDockingEventFromJSONTyped,
    SpacecraftFlightSerializerForDockingEventToJSON,
} from './SpacecraftFlightSerializerForDockingEvent';

/**
 * 
 * @export
 * @interface DockingEvent
 */
export interface DockingEvent {
    /**
     * 
     * @type {number}
     * @memberof DockingEvent
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof DockingEvent
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof DockingEvent
     */
    launchId: string;
    /**
     * 
     * @type {Date}
     * @memberof DockingEvent
     */
    docking: Date;
    /**
     * 
     * @type {Date}
     * @memberof DockingEvent
     */
    departure?: Date | null;
    /**
     * 
     * @type {SpacecraftFlightSerializerForDockingEvent}
     * @memberof DockingEvent
     */
    readonly flightVehicle: SpacecraftFlightSerializerForDockingEvent | null;
    /**
     * 
     * @type {DockingLocation}
     * @memberof DockingEvent
     */
    readonly dockingLocation: DockingLocation | null;
}

export function DockingEventFromJSON(json: any): DockingEvent {
    return DockingEventFromJSONTyped(json, false);
}

export function DockingEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockingEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'launchId': json['launch_id'],
        'docking': (new Date(json['docking'])),
        'departure': !exists(json, 'departure') ? undefined : (json['departure'] === null ? null : new Date(json['departure'])),
        'flightVehicle': SpacecraftFlightSerializerForDockingEventFromJSON(json['flight_vehicle']),
        'dockingLocation': DockingLocationFromJSON(json['docking_location']),
    };
}

export function DockingEventToJSON(value?: DockingEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'launch_id': value.launchId,
        'docking': (value.docking.toISOString()),
        'departure': value.departure === undefined ? undefined : (value.departure === null ? null : value.departure.toISOString()),
    };
}

