/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AstronautFlightForExpedition,
    AstronautFlightForExpeditionFromJSON,
    AstronautFlightForExpeditionFromJSONTyped,
    AstronautFlightForExpeditionToJSON,
} from './AstronautFlightForExpedition';
import {
    MissionPatch,
    MissionPatchFromJSON,
    MissionPatchFromJSONTyped,
    MissionPatchToJSON,
} from './MissionPatch';
import {
    SpaceStationDetailedSerializerForExpedition,
    SpaceStationDetailedSerializerForExpeditionFromJSON,
    SpaceStationDetailedSerializerForExpeditionFromJSONTyped,
    SpaceStationDetailedSerializerForExpeditionToJSON,
} from './SpaceStationDetailedSerializerForExpedition';

/**
 * 
 * @export
 * @interface ExpeditionDetail
 */
export interface ExpeditionDetail {
    /**
     * 
     * @type {number}
     * @memberof ExpeditionDetail
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof ExpeditionDetail
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof ExpeditionDetail
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof ExpeditionDetail
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExpeditionDetail
     */
    end?: Date | null;
    /**
     * 
     * @type {SpaceStationDetailedSerializerForExpedition}
     * @memberof ExpeditionDetail
     */
    readonly spacestation: SpaceStationDetailedSerializerForExpedition | null;
    /**
     * 
     * @type {Array<AstronautFlightForExpedition>}
     * @memberof ExpeditionDetail
     */
    readonly crew: Array<AstronautFlightForExpedition>;
    /**
     * 
     * @type {Array<MissionPatch>}
     * @memberof ExpeditionDetail
     */
    readonly missionPatches: Array<MissionPatch>;
}

export function ExpeditionDetailFromJSON(json: any): ExpeditionDetail {
    return ExpeditionDetailFromJSONTyped(json, false);
}

export function ExpeditionDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpeditionDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'start': (new Date(json['start'])),
        'end': !exists(json, 'end') ? undefined : (json['end'] === null ? null : new Date(json['end'])),
        'spacestation': SpaceStationDetailedSerializerForExpeditionFromJSON(json['spacestation']),
        'crew': ((json['crew'] as Array<any>).map(AstronautFlightForExpeditionFromJSON)),
        'missionPatches': ((json['mission_patches'] as Array<any>).map(MissionPatchFromJSON)),
    };
}

export function ExpeditionDetailToJSON(value?: ExpeditionDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'start': (value.start.toISOString()),
        'end': value.end === undefined ? undefined : (value.end === null ? null : value.end.toISOString()),
    };
}

