/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Landing,
    LandingFromJSON,
    LandingFromJSONTyped,
    LandingToJSON,
} from './Landing';
import {
    LaunchSerializerMini,
    LaunchSerializerMiniFromJSON,
    LaunchSerializerMiniFromJSONTyped,
    LaunchSerializerMiniToJSON,
} from './LaunchSerializerMini';
import {
    LauncherDetailed,
    LauncherDetailedFromJSON,
    LauncherDetailedFromJSONTyped,
    LauncherDetailedToJSON,
} from './LauncherDetailed';

/**
 * 
 * @export
 * @interface FirstStage
 */
export interface FirstStage {
    /**
     * 
     * @type {number}
     * @memberof FirstStage
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof FirstStage
     */
    readonly type: string;
    /**
     * 
     * @type {boolean}
     * @memberof FirstStage
     */
    reused?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof FirstStage
     */
    readonly launcherFlightNumber: number;
    /**
     * 
     * @type {LauncherDetailed}
     * @memberof FirstStage
     */
    readonly launcher: LauncherDetailed | null;
    /**
     * 
     * @type {Landing}
     * @memberof FirstStage
     */
    readonly landing: Landing | null;
    /**
     * 
     * @type {Date}
     * @memberof FirstStage
     */
    readonly previousFlightDate: Date;
    /**
     * 
     * @type {number}
     * @memberof FirstStage
     */
    readonly turnAroundTimeDays: number;
    /**
     * 
     * @type {LaunchSerializerMini}
     * @memberof FirstStage
     */
    readonly previousFlight: LaunchSerializerMini | null;
}

export function FirstStageFromJSON(json: any): FirstStage {
    return FirstStageFromJSONTyped(json, false);
}

export function FirstStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirstStage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'reused': !exists(json, 'reused') ? undefined : json['reused'],
        'launcherFlightNumber': json['launcher_flight_number'],
        'launcher': LauncherDetailedFromJSON(json['launcher']),
        'landing': LandingFromJSON(json['landing']),
        'previousFlightDate': (new Date(json['previous_flight_date'])),
        'turnAroundTimeDays': json['turn_around_time_days'],
        'previousFlight': LaunchSerializerMiniFromJSON(json['previous_flight']),
    };
}

export function FirstStageToJSON(value?: FirstStage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reused': value.reused,
    };
}

