/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgencySerializerDetailedCommon,
    AgencySerializerDetailedCommonFromJSON,
    AgencySerializerDetailedCommonFromJSONTyped,
    AgencySerializerDetailedCommonToJSON,
} from './AgencySerializerDetailedCommon';
import {
    InfoURL,
    InfoURLFromJSON,
    InfoURLFromJSONTyped,
    InfoURLToJSON,
} from './InfoURL';
import {
    LaunchStatus,
    LaunchStatusFromJSON,
    LaunchStatusFromJSONTyped,
    LaunchStatusToJSON,
} from './LaunchStatus';
import {
    Mission,
    MissionFromJSON,
    MissionFromJSONTyped,
    MissionToJSON,
} from './Mission';
import {
    MissionPatch,
    MissionPatchFromJSON,
    MissionPatchFromJSONTyped,
    MissionPatchToJSON,
} from './MissionPatch';
import {
    Pad,
    PadFromJSON,
    PadFromJSONTyped,
    PadToJSON,
} from './Pad';
import {
    Program,
    ProgramFromJSON,
    ProgramFromJSONTyped,
    ProgramToJSON,
} from './Program';
import {
    RocketDetailed,
    RocketDetailedFromJSON,
    RocketDetailedFromJSONTyped,
    RocketDetailedToJSON,
} from './RocketDetailed';
import {
    Update,
    UpdateFromJSON,
    UpdateFromJSONTyped,
    UpdateToJSON,
} from './Update';
import {
    VidURL,
    VidURLFromJSON,
    VidURLFromJSONTyped,
    VidURLToJSON,
} from './VidURL';

/**
 * 
 * @export
 * @interface LaunchDetailed
 */
export interface LaunchDetailed {
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly flightclubUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly rSpacexApiId: string | null;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly name: string;
    /**
     * 
     * @type {LaunchStatus}
     * @memberof LaunchDetailed
     */
    readonly status: LaunchStatus | null;
    /**
     * 
     * @type {Date}
     * @memberof LaunchDetailed
     */
    readonly lastUpdated: Date;
    /**
     * 
     * @type {Array<Update>}
     * @memberof LaunchDetailed
     */
    readonly updates: Array<Update>;
    /**
     * 
     * @type {Date}
     * @memberof LaunchDetailed
     */
    readonly net: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof LaunchDetailed
     */
    readonly windowEnd: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof LaunchDetailed
     */
    readonly windowStart: Date | null;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly probability: number | null;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly holdreason: string | null;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly failreason: string | null;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly hashtag: string | null;
    /**
     * 
     * @type {AgencySerializerDetailedCommon}
     * @memberof LaunchDetailed
     */
    readonly launchServiceProvider: AgencySerializerDetailedCommon | null;
    /**
     * 
     * @type {RocketDetailed}
     * @memberof LaunchDetailed
     */
    readonly rocket: RocketDetailed | null;
    /**
     * 
     * @type {Mission}
     * @memberof LaunchDetailed
     */
    readonly mission: Mission | null;
    /**
     * 
     * @type {Pad}
     * @memberof LaunchDetailed
     */
    readonly pad: Pad | null;
    /**
     * 
     * @type {Array<InfoURL>}
     * @memberof LaunchDetailed
     */
    readonly infoURLs: Array<InfoURL>;
    /**
     * 
     * @type {Array<VidURL>}
     * @memberof LaunchDetailed
     */
    readonly vidURLs: Array<VidURL>;
    /**
     * 
     * @type {boolean}
     * @memberof LaunchDetailed
     */
    readonly webcastLive: boolean;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly image: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchDetailed
     */
    readonly infographic: string;
    /**
     * 
     * @type {Array<Program>}
     * @memberof LaunchDetailed
     */
    readonly program: Array<Program>;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly orbitalLaunchAttemptCount: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly locationLaunchAttemptCount: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly padLaunchAttemptCount: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly agencyLaunchAttemptCount: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly orbitalLaunchAttemptCountYear: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly locationLaunchAttemptCountYear: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly padLaunchAttemptCountYear: number;
    /**
     * 
     * @type {number}
     * @memberof LaunchDetailed
     */
    readonly agencyLaunchAttemptCountYear: number;
    /**
     * 
     * @type {Array<MissionPatch>}
     * @memberof LaunchDetailed
     */
    readonly missionPatches: Array<MissionPatch>;
}

export function LaunchDetailedFromJSON(json: any): LaunchDetailed {
    return LaunchDetailedFromJSONTyped(json, false);
}

export function LaunchDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchDetailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'slug': json['slug'],
        'flightclubUrl': json['flightclub_url'],
        'rSpacexApiId': json['r_spacex_api_id'],
        'name': json['name'],
        'status': LaunchStatusFromJSON(json['status']),
        'lastUpdated': (new Date(json['last_updated'])),
        'updates': ((json['updates'] as Array<any>).map(UpdateFromJSON)),
        'net': (json['net'] === null ? null : new Date(json['net'])),
        'windowEnd': (json['window_end'] === null ? null : new Date(json['window_end'])),
        'windowStart': (json['window_start'] === null ? null : new Date(json['window_start'])),
        'probability': json['probability'],
        'holdreason': json['holdreason'],
        'failreason': json['failreason'],
        'hashtag': json['hashtag'],
        'launchServiceProvider': AgencySerializerDetailedCommonFromJSON(json['launch_service_provider']),
        'rocket': RocketDetailedFromJSON(json['rocket']),
        'mission': MissionFromJSON(json['mission']),
        'pad': PadFromJSON(json['pad']),
        'infoURLs': ((json['infoURLs'] as Array<any>).map(InfoURLFromJSON)),
        'vidURLs': ((json['vidURLs'] as Array<any>).map(VidURLFromJSON)),
        'webcastLive': json['webcast_live'],
        'image': json['image'],
        'infographic': json['infographic'],
        'program': ((json['program'] as Array<any>).map(ProgramFromJSON)),
        'orbitalLaunchAttemptCount': json['orbital_launch_attempt_count'],
        'locationLaunchAttemptCount': json['location_launch_attempt_count'],
        'padLaunchAttemptCount': json['pad_launch_attempt_count'],
        'agencyLaunchAttemptCount': json['agency_launch_attempt_count'],
        'orbitalLaunchAttemptCountYear': json['orbital_launch_attempt_count_year'],
        'locationLaunchAttemptCountYear': json['location_launch_attempt_count_year'],
        'padLaunchAttemptCountYear': json['pad_launch_attempt_count_year'],
        'agencyLaunchAttemptCountYear': json['agency_launch_attempt_count_year'],
        'missionPatches': ((json['mission_patches'] as Array<any>).map(MissionPatchFromJSON)),
    };
}

export function LaunchDetailedToJSON(value?: LaunchDetailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
    };
}

