/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgencySerializerMini,
    AgencySerializerMiniFromJSON,
    AgencySerializerMiniFromJSONTyped,
    AgencySerializerMiniToJSON,
} from './AgencySerializerMini';

/**
 * 
 * @export
 * @interface MissionPatch
 */
export interface MissionPatch {
    /**
     * 
     * @type {number}
     * @memberof MissionPatch
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof MissionPatch
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MissionPatch
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof MissionPatch
     */
    imageUrl: string;
    /**
     * 
     * @type {AgencySerializerMini}
     * @memberof MissionPatch
     */
    readonly agency: AgencySerializerMini | null;
}

export function MissionPatchFromJSON(json: any): MissionPatch {
    return MissionPatchFromJSONTyped(json, false);
}

export function MissionPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): MissionPatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
        'imageUrl': json['image_url'],
        'agency': AgencySerializerMiniFromJSON(json['agency']),
    };
}

export function MissionPatchToJSON(value?: MissionPatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'priority': value.priority,
        'image_url': value.imageUrl,
    };
}

