/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FirstStage,
    FirstStageFromJSON,
    FirstStageFromJSONTyped,
    FirstStageToJSON,
} from './FirstStage';
import {
    LauncherConfigDetail,
    LauncherConfigDetailFromJSON,
    LauncherConfigDetailFromJSONTyped,
    LauncherConfigDetailToJSON,
} from './LauncherConfigDetail';
import {
    SpacecraftFlightDetailedSerializerForLaunch,
    SpacecraftFlightDetailedSerializerForLaunchFromJSON,
    SpacecraftFlightDetailedSerializerForLaunchFromJSONTyped,
    SpacecraftFlightDetailedSerializerForLaunchToJSON,
} from './SpacecraftFlightDetailedSerializerForLaunch';

/**
 * 
 * @export
 * @interface RocketDetailed
 */
export interface RocketDetailed {
    /**
     * 
     * @type {number}
     * @memberof RocketDetailed
     */
    readonly id: number;
    /**
     * 
     * @type {LauncherConfigDetail}
     * @memberof RocketDetailed
     */
    readonly _configuration: LauncherConfigDetail | null;
    /**
     * 
     * @type {Array<FirstStage>}
     * @memberof RocketDetailed
     */
    readonly launcherStage: Array<FirstStage>;
    /**
     * 
     * @type {SpacecraftFlightDetailedSerializerForLaunch}
     * @memberof RocketDetailed
     */
    readonly spacecraftStage: SpacecraftFlightDetailedSerializerForLaunch | null;
}

export function RocketDetailedFromJSON(json: any): RocketDetailed {
    return RocketDetailedFromJSONTyped(json, false);
}

export function RocketDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): RocketDetailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        '_configuration': LauncherConfigDetailFromJSON(json['configuration']),
        'launcherStage': ((json['launcher_stage'] as Array<any>).map(FirstStageFromJSON)),
        'spacecraftStage': SpacecraftFlightDetailedSerializerForLaunchFromJSON(json['spacecraft_stage']),
    };
}

export function RocketDetailedToJSON(value?: RocketDetailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

