/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpacecraftDetailedNoFlights,
    SpacecraftDetailedNoFlightsFromJSON,
    SpacecraftDetailedNoFlightsFromJSONTyped,
    SpacecraftDetailedNoFlightsToJSON,
} from './SpacecraftDetailedNoFlights';

/**
 * 
 * @export
 * @interface SpacecraftFlightSerializerForDockingEventDetailed
 */
export interface SpacecraftFlightSerializerForDockingEventDetailed {
    /**
     * 
     * @type {number}
     * @memberof SpacecraftFlightSerializerForDockingEventDetailed
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftFlightSerializerForDockingEventDetailed
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftFlightSerializerForDockingEventDetailed
     */
    destination?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SpacecraftFlightSerializerForDockingEventDetailed
     */
    missionEnd?: Date | null;
    /**
     * 
     * @type {SpacecraftDetailedNoFlights}
     * @memberof SpacecraftFlightSerializerForDockingEventDetailed
     */
    readonly spacecraft: SpacecraftDetailedNoFlights | null;
}

export function SpacecraftFlightSerializerForDockingEventDetailedFromJSON(json: any): SpacecraftFlightSerializerForDockingEventDetailed {
    return SpacecraftFlightSerializerForDockingEventDetailedFromJSONTyped(json, false);
}

export function SpacecraftFlightSerializerForDockingEventDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacecraftFlightSerializerForDockingEventDetailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'destination': !exists(json, 'destination') ? undefined : json['destination'],
        'missionEnd': !exists(json, 'mission_end') ? undefined : (json['mission_end'] === null ? null : new Date(json['mission_end'])),
        'spacecraft': SpacecraftDetailedNoFlightsFromJSON(json['spacecraft']),
    };
}

export function SpacecraftFlightSerializerForDockingEventDetailedToJSON(value?: SpacecraftFlightSerializerForDockingEventDetailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'destination': value.destination,
        'mission_end': value.missionEnd === undefined ? undefined : (value.missionEnd === null ? null : value.missionEnd.toISOString()),
    };
}

