/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agency,
    AgencyFromJSON,
    AgencyFromJSONTyped,
    AgencyToJSON,
} from './Agency';
import {
    SpacecraftConfigType,
    SpacecraftConfigTypeFromJSON,
    SpacecraftConfigTypeFromJSONTyped,
    SpacecraftConfigTypeToJSON,
} from './SpacecraftConfigType';

/**
 * 
 * @export
 * @interface SpacecraftConfigurationDetail
 */
export interface SpacecraftConfigurationDetail {
    /**
     * 
     * @type {number}
     * @memberof SpacecraftConfigurationDetail
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    name: string;
    /**
     * 
     * @type {SpacecraftConfigType}
     * @memberof SpacecraftConfigurationDetail
     */
    readonly type: SpacecraftConfigType | null;
    /**
     * 
     * @type {Agency}
     * @memberof SpacecraftConfigurationDetail
     */
    readonly agency: Agency | null;
    /**
     * 
     * @type {boolean}
     * @memberof SpacecraftConfigurationDetail
     */
    inUse?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    capability?: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    history?: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    details?: string;
    /**
     * 
     * @type {Date}
     * @memberof SpacecraftConfigurationDetail
     */
    maidenFlight?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof SpacecraftConfigurationDetail
     */
    height?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SpacecraftConfigurationDetail
     */
    diameter?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof SpacecraftConfigurationDetail
     */
    humanRated?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SpacecraftConfigurationDetail
     */
    crewCapacity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SpacecraftConfigurationDetail
     */
    payloadCapacity?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    flightLife?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    nationUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    wikiLink?: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftConfigurationDetail
     */
    infoLink?: string;
}

export function SpacecraftConfigurationDetailFromJSON(json: any): SpacecraftConfigurationDetail {
    return SpacecraftConfigurationDetailFromJSONTyped(json, false);
}

export function SpacecraftConfigurationDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacecraftConfigurationDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'type': SpacecraftConfigTypeFromJSON(json['type']),
        'agency': AgencyFromJSON(json['agency']),
        'inUse': !exists(json, 'in_use') ? undefined : json['in_use'],
        'capability': !exists(json, 'capability') ? undefined : json['capability'],
        'history': !exists(json, 'history') ? undefined : json['history'],
        'details': !exists(json, 'details') ? undefined : json['details'],
        'maidenFlight': !exists(json, 'maiden_flight') ? undefined : (json['maiden_flight'] === null ? null : new Date(json['maiden_flight'])),
        'height': !exists(json, 'height') ? undefined : json['height'],
        'diameter': !exists(json, 'diameter') ? undefined : json['diameter'],
        'humanRated': !exists(json, 'human_rated') ? undefined : json['human_rated'],
        'crewCapacity': !exists(json, 'crew_capacity') ? undefined : json['crew_capacity'],
        'payloadCapacity': !exists(json, 'payload_capacity') ? undefined : json['payload_capacity'],
        'flightLife': !exists(json, 'flight_life') ? undefined : json['flight_life'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
        'nationUrl': !exists(json, 'nation_url') ? undefined : json['nation_url'],
        'wikiLink': !exists(json, 'wiki_link') ? undefined : json['wiki_link'],
        'infoLink': !exists(json, 'info_link') ? undefined : json['info_link'],
    };
}

export function SpacecraftConfigurationDetailToJSON(value?: SpacecraftConfigurationDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'in_use': value.inUse,
        'capability': value.capability,
        'history': value.history,
        'details': value.details,
        'maiden_flight': value.maidenFlight === undefined ? undefined : (value.maidenFlight === null ? null : value.maidenFlight.toISOString().substr(0,10)),
        'height': value.height,
        'diameter': value.diameter,
        'human_rated': value.humanRated,
        'crew_capacity': value.crewCapacity,
        'payload_capacity': value.payloadCapacity,
        'flight_life': value.flightLife,
        'image_url': value.imageUrl,
        'nation_url': value.nationUrl,
        'wiki_link': value.wikiLink,
        'info_link': value.infoLink,
    };
}

