/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpacecraftConfigurationDetail,
    SpacecraftConfigurationDetailFromJSON,
    SpacecraftConfigurationDetailFromJSONTyped,
    SpacecraftConfigurationDetailToJSON,
} from './SpacecraftConfigurationDetail';
import {
    SpacecraftFlight,
    SpacecraftFlightFromJSON,
    SpacecraftFlightFromJSONTyped,
    SpacecraftFlightToJSON,
} from './SpacecraftFlight';
import {
    SpacecraftStatus,
    SpacecraftStatusFromJSON,
    SpacecraftStatusFromJSONTyped,
    SpacecraftStatusToJSON,
} from './SpacecraftStatus';

/**
 * 
 * @export
 * @interface SpacecraftDetailed
 */
export interface SpacecraftDetailed {
    /**
     * 
     * @type {number}
     * @memberof SpacecraftDetailed
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftDetailed
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftDetailed
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftDetailed
     */
    serialNumber?: string | null;
    /**
     * 
     * @type {SpacecraftStatus}
     * @memberof SpacecraftDetailed
     */
    readonly status: SpacecraftStatus | null;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftDetailed
     */
    description: string;
    /**
     * 
     * @type {SpacecraftConfigurationDetail}
     * @memberof SpacecraftDetailed
     */
    readonly spacecraftConfig: SpacecraftConfigurationDetail | null;
    /**
     * 
     * @type {Array<SpacecraftFlight>}
     * @memberof SpacecraftDetailed
     */
    readonly flights: Array<SpacecraftFlight>;
}

export function SpacecraftDetailedFromJSON(json: any): SpacecraftDetailed {
    return SpacecraftDetailedFromJSONTyped(json, false);
}

export function SpacecraftDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacecraftDetailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'serialNumber': !exists(json, 'serial_number') ? undefined : json['serial_number'],
        'status': SpacecraftStatusFromJSON(json['status']),
        'description': json['description'],
        'spacecraftConfig': SpacecraftConfigurationDetailFromJSON(json['spacecraft_config']),
        'flights': ((json['flights'] as Array<any>).map(SpacecraftFlightFromJSON)),
    };
}

export function SpacecraftDetailedToJSON(value?: SpacecraftDetailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'serial_number': value.serialNumber,
        'description': value.description,
    };
}

