/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LaunchSerializerCommon,
    LaunchSerializerCommonFromJSON,
    LaunchSerializerCommonFromJSONTyped,
    LaunchSerializerCommonToJSON,
} from './LaunchSerializerCommon';
import {
    SpacecraftDetailedNoFlights,
    SpacecraftDetailedNoFlightsFromJSON,
    SpacecraftDetailedNoFlightsFromJSONTyped,
    SpacecraftDetailedNoFlightsToJSON,
} from './SpacecraftDetailedNoFlights';

/**
 * 
 * @export
 * @interface SpacecraftFlightForDockingEvent
 */
export interface SpacecraftFlightForDockingEvent {
    /**
     * 
     * @type {number}
     * @memberof SpacecraftFlightForDockingEvent
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftFlightForDockingEvent
     */
    readonly url: string;
    /**
     * 
     * @type {SpacecraftDetailedNoFlights}
     * @memberof SpacecraftFlightForDockingEvent
     */
    readonly spacecraft: SpacecraftDetailedNoFlights | null;
    /**
     * 
     * @type {LaunchSerializerCommon}
     * @memberof SpacecraftFlightForDockingEvent
     */
    readonly launch: LaunchSerializerCommon | null;
}

export function SpacecraftFlightForDockingEventFromJSON(json: any): SpacecraftFlightForDockingEvent {
    return SpacecraftFlightForDockingEventFromJSONTyped(json, false);
}

export function SpacecraftFlightForDockingEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacecraftFlightForDockingEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'spacecraft': SpacecraftDetailedNoFlightsFromJSON(json['spacecraft']),
        'launch': LaunchSerializerCommonFromJSON(json['launch']),
    };
}

export function SpacecraftFlightForDockingEventToJSON(value?: SpacecraftFlightForDockingEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

