/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LaunchSerializerCommon,
    LaunchSerializerCommonFromJSON,
    LaunchSerializerCommonFromJSONTyped,
    LaunchSerializerCommonToJSON,
} from './LaunchSerializerCommon';
import {
    Spacecraft,
    SpacecraftFromJSON,
    SpacecraftFromJSONTyped,
    SpacecraftToJSON,
} from './Spacecraft';

/**
 * 
 * @export
 * @interface SpacecraftFlight
 */
export interface SpacecraftFlight {
    /**
     * 
     * @type {number}
     * @memberof SpacecraftFlight
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftFlight
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftFlight
     */
    destination?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SpacecraftFlight
     */
    missionEnd?: Date | null;
    /**
     * 
     * @type {Spacecraft}
     * @memberof SpacecraftFlight
     */
    readonly spacecraft: Spacecraft | null;
    /**
     * 
     * @type {LaunchSerializerCommon}
     * @memberof SpacecraftFlight
     */
    readonly launch: LaunchSerializerCommon | null;
}

export function SpacecraftFlightFromJSON(json: any): SpacecraftFlight {
    return SpacecraftFlightFromJSONTyped(json, false);
}

export function SpacecraftFlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacecraftFlight {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'destination': !exists(json, 'destination') ? undefined : json['destination'],
        'missionEnd': !exists(json, 'mission_end') ? undefined : (json['mission_end'] === null ? null : new Date(json['mission_end'])),
        'spacecraft': SpacecraftFromJSON(json['spacecraft']),
        'launch': LaunchSerializerCommonFromJSON(json['launch']),
    };
}

export function SpacecraftFlightToJSON(value?: SpacecraftFlight | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'destination': value.destination,
        'mission_end': value.missionEnd === undefined ? undefined : (value.missionEnd === null ? null : value.missionEnd.toISOString()),
    };
}

