/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LauncherConfigDetailSerializerForAgency,
    LauncherConfigDetailSerializerForAgencyFromJSON,
    LauncherConfigDetailSerializerForAgencyFromJSONTyped,
    LauncherConfigDetailSerializerForAgencyToJSON,
} from './LauncherConfigDetailSerializerForAgency';
import {
    SpacecraftConfigurationDetail,
    SpacecraftConfigurationDetailFromJSON,
    SpacecraftConfigurationDetailFromJSONTyped,
    SpacecraftConfigurationDetailToJSON,
} from './SpacecraftConfigurationDetail';

/**
 * 
 * @export
 * @interface AgencySerializerDetailed
 */
export interface AgencySerializerDetailed {
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof AgencySerializerDetailed
     */
    featured?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    abbrev?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    administrator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    foundingYear?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    launchers?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    spacecraft?: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    readonly parent: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    readonly launchLibraryUrl: string;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly totalLaunchCount: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly successfulLaunches: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly consecutiveSuccessfulLaunches: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly failedLaunches: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly pendingLaunches: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly successfulLandings: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly failedLandings: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly attemptedLandings: number;
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerDetailed
     */
    readonly consecutiveSuccessfulLandings: number;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    infoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    wikiUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerDetailed
     */
    nationUrl?: string | null;
    /**
     * 
     * @type {Array<LauncherConfigDetailSerializerForAgency>}
     * @memberof AgencySerializerDetailed
     */
    readonly launcherList: Array<LauncherConfigDetailSerializerForAgency>;
    /**
     * 
     * @type {Array<SpacecraftConfigurationDetail>}
     * @memberof AgencySerializerDetailed
     */
    readonly spacecraftList: Array<SpacecraftConfigurationDetail>;
}

export function AgencySerializerDetailedFromJSON(json: any): AgencySerializerDetailed {
    return AgencySerializerDetailedFromJSONTyped(json, false);
}

export function AgencySerializerDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencySerializerDetailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'featured': !exists(json, 'featured') ? undefined : json['featured'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
        'abbrev': !exists(json, 'abbrev') ? undefined : json['abbrev'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'administrator': !exists(json, 'administrator') ? undefined : json['administrator'],
        'foundingYear': !exists(json, 'founding_year') ? undefined : json['founding_year'],
        'launchers': !exists(json, 'launchers') ? undefined : json['launchers'],
        'spacecraft': !exists(json, 'spacecraft') ? undefined : json['spacecraft'],
        'parent': json['parent'],
        'launchLibraryUrl': json['launch_library_url'],
        'totalLaunchCount': json['total_launch_count'],
        'successfulLaunches': json['successful_launches'],
        'consecutiveSuccessfulLaunches': json['consecutive_successful_launches'],
        'failedLaunches': json['failed_launches'],
        'pendingLaunches': json['pending_launches'],
        'successfulLandings': json['successful_landings'],
        'failedLandings': json['failed_landings'],
        'attemptedLandings': json['attempted_landings'],
        'consecutiveSuccessfulLandings': json['consecutive_successful_landings'],
        'infoUrl': !exists(json, 'info_url') ? undefined : json['info_url'],
        'wikiUrl': !exists(json, 'wiki_url') ? undefined : json['wiki_url'],
        'logoUrl': !exists(json, 'logo_url') ? undefined : json['logo_url'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
        'nationUrl': !exists(json, 'nation_url') ? undefined : json['nation_url'],
        'launcherList': ((json['launcher_list'] as Array<any>).map(LauncherConfigDetailSerializerForAgencyFromJSON)),
        'spacecraftList': ((json['spacecraft_list'] as Array<any>).map(SpacecraftConfigurationDetailFromJSON)),
    };
}

export function AgencySerializerDetailedToJSON(value?: AgencySerializerDetailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'featured': value.featured,
        'type': value.type,
        'country_code': value.countryCode,
        'abbrev': value.abbrev,
        'description': value.description,
        'administrator': value.administrator,
        'founding_year': value.foundingYear,
        'launchers': value.launchers,
        'spacecraft': value.spacecraft,
        'info_url': value.infoUrl,
        'wiki_url': value.wikiUrl,
        'logo_url': value.logoUrl,
        'image_url': value.imageUrl,
        'nation_url': value.nationUrl,
    };
}

