/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgencySerializerMini
 */
export interface AgencySerializerMini {
    /**
     * 
     * @type {number}
     * @memberof AgencySerializerMini
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerMini
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerMini
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AgencySerializerMini
     */
    type?: string | null;
}

export function AgencySerializerMiniFromJSON(json: any): AgencySerializerMini {
    return AgencySerializerMiniFromJSONTyped(json, false);
}

export function AgencySerializerMiniFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgencySerializerMini {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function AgencySerializerMiniToJSON(value?: AgencySerializerMini | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
    };
}

