/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Agency
 */
export interface Agency {
    /**
     * 
     * @type {number}
     * @memberof Agency
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof Agency
     */
    featured?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    abbrev?: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    administrator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    foundingYear?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    launchers?: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    spacecraft?: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    readonly parent: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    imageUrl?: string | null;
}

export function AgencyFromJSON(json: any): Agency {
    return AgencyFromJSONTyped(json, false);
}

export function AgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'featured': !exists(json, 'featured') ? undefined : json['featured'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
        'abbrev': !exists(json, 'abbrev') ? undefined : json['abbrev'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'administrator': !exists(json, 'administrator') ? undefined : json['administrator'],
        'foundingYear': !exists(json, 'founding_year') ? undefined : json['founding_year'],
        'launchers': !exists(json, 'launchers') ? undefined : json['launchers'],
        'spacecraft': !exists(json, 'spacecraft') ? undefined : json['spacecraft'],
        'parent': json['parent'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
    };
}

export function AgencyToJSON(value?: Agency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'featured': value.featured,
        'type': value.type,
        'country_code': value.countryCode,
        'abbrev': value.abbrev,
        'description': value.description,
        'administrator': value.administrator,
        'founding_year': value.foundingYear,
        'launchers': value.launchers,
        'spacecraft': value.spacecraft,
        'image_url': value.imageUrl,
    };
}

