/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgencySerializerMini,
    AgencySerializerMiniFromJSON,
    AgencySerializerMiniFromJSONTyped,
    AgencySerializerMiniToJSON,
} from './AgencySerializerMini';
import {
    AstronautStatus,
    AstronautStatusFromJSON,
    AstronautStatusFromJSONTyped,
    AstronautStatusToJSON,
} from './AstronautStatus';
import {
    AstronautType,
    AstronautTypeFromJSON,
    AstronautTypeFromJSONTyped,
    AstronautTypeToJSON,
} from './AstronautType';
import {
    LaunchSerializerCommon,
    LaunchSerializerCommonFromJSON,
    LaunchSerializerCommonFromJSONTyped,
    LaunchSerializerCommonToJSON,
} from './LaunchSerializerCommon';
import {
    SpacecraftFlight,
    SpacecraftFlightFromJSON,
    SpacecraftFlightFromJSONTyped,
    SpacecraftFlightToJSON,
} from './SpacecraftFlight';

/**
 * 
 * @export
 * @interface AstronautDetailed
 */
export interface AstronautDetailed {
    /**
     * 
     * @type {number}
     * @memberof AstronautDetailed
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    name: string;
    /**
     * 
     * @type {AstronautStatus}
     * @memberof AstronautDetailed
     */
    readonly status: AstronautStatus | null;
    /**
     * 
     * @type {AstronautType}
     * @memberof AstronautDetailed
     */
    readonly type: AstronautType | null;
    /**
     * 
     * @type {AgencySerializerMini}
     * @memberof AstronautDetailed
     */
    readonly agency: AgencySerializerMini | null;
    /**
     * 
     * @type {Date}
     * @memberof AstronautDetailed
     */
    dateOfBirth?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AstronautDetailed
     */
    dateOfDeath?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    nationality: string;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    twitter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    instagram?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    bio: string;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    profileImage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    readonly profileImageThumbnail: string;
    /**
     * 
     * @type {string}
     * @memberof AstronautDetailed
     */
    wiki?: string | null;
    /**
     * 
     * @type {Array<LaunchSerializerCommon>}
     * @memberof AstronautDetailed
     */
    readonly flights: Array<LaunchSerializerCommon>;
    /**
     * 
     * @type {Array<SpacecraftFlight>}
     * @memberof AstronautDetailed
     */
    readonly landings: Array<SpacecraftFlight>;
    /**
     * 
     * @type {Date}
     * @memberof AstronautDetailed
     */
    readonly lastFlight: Date;
    /**
     * 
     * @type {Date}
     * @memberof AstronautDetailed
     */
    readonly firstFlight: Date;
}

export function AstronautDetailedFromJSON(json: any): AstronautDetailed {
    return AstronautDetailedFromJSONTyped(json, false);
}

export function AstronautDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AstronautDetailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'status': AstronautStatusFromJSON(json['status']),
        'type': AstronautTypeFromJSON(json['type']),
        'agency': AgencySerializerMiniFromJSON(json['agency']),
        'dateOfBirth': !exists(json, 'date_of_birth') ? undefined : (json['date_of_birth'] === null ? null : new Date(json['date_of_birth'])),
        'dateOfDeath': !exists(json, 'date_of_death') ? undefined : (json['date_of_death'] === null ? null : new Date(json['date_of_death'])),
        'nationality': json['nationality'],
        'twitter': !exists(json, 'twitter') ? undefined : json['twitter'],
        'instagram': !exists(json, 'instagram') ? undefined : json['instagram'],
        'bio': json['bio'],
        'profileImage': !exists(json, 'profile_image') ? undefined : json['profile_image'],
        'profileImageThumbnail': json['profile_image_thumbnail'],
        'wiki': !exists(json, 'wiki') ? undefined : json['wiki'],
        'flights': ((json['flights'] as Array<any>).map(LaunchSerializerCommonFromJSON)),
        'landings': ((json['landings'] as Array<any>).map(SpacecraftFlightFromJSON)),
        'lastFlight': (new Date(json['last_flight'])),
        'firstFlight': (new Date(json['first_flight'])),
    };
}

export function AstronautDetailedToJSON(value?: AstronautDetailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'date_of_birth': value.dateOfBirth === undefined ? undefined : (value.dateOfBirth === null ? null : value.dateOfBirth.toISOString().substr(0,10)),
        'date_of_death': value.dateOfDeath === undefined ? undefined : (value.dateOfDeath === null ? null : value.dateOfDeath.toISOString().substr(0,10)),
        'nationality': value.nationality,
        'twitter': value.twitter,
        'instagram': value.instagram,
        'bio': value.bio,
        'profile_image': value.profileImage,
        'wiki': value.wiki,
    };
}

