/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DockingLocation,
    DockingLocationFromJSON,
    DockingLocationFromJSONTyped,
    DockingLocationToJSON,
} from './DockingLocation';
import {
    SpaceStationSerializerForCommon,
    SpaceStationSerializerForCommonFromJSON,
    SpaceStationSerializerForCommonFromJSONTyped,
    SpaceStationSerializerForCommonToJSON,
} from './SpaceStationSerializerForCommon';

/**
 * 
 * @export
 * @interface DockingEventSerializerForSpacecraftFlight
 */
export interface DockingEventSerializerForSpacecraftFlight {
    /**
     * 
     * @type {SpaceStationSerializerForCommon}
     * @memberof DockingEventSerializerForSpacecraftFlight
     */
    readonly spacestation: SpaceStationSerializerForCommon | null;
    /**
     * 
     * @type {Date}
     * @memberof DockingEventSerializerForSpacecraftFlight
     */
    docking: Date;
    /**
     * 
     * @type {Date}
     * @memberof DockingEventSerializerForSpacecraftFlight
     */
    departure?: Date | null;
    /**
     * 
     * @type {DockingLocation}
     * @memberof DockingEventSerializerForSpacecraftFlight
     */
    readonly dockingLocation: DockingLocation | null;
}

export function DockingEventSerializerForSpacecraftFlightFromJSON(json: any): DockingEventSerializerForSpacecraftFlight {
    return DockingEventSerializerForSpacecraftFlightFromJSONTyped(json, false);
}

export function DockingEventSerializerForSpacecraftFlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockingEventSerializerForSpacecraftFlight {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spacestation': SpaceStationSerializerForCommonFromJSON(json['spacestation']),
        'docking': (new Date(json['docking'])),
        'departure': !exists(json, 'departure') ? undefined : (json['departure'] === null ? null : new Date(json['departure'])),
        'dockingLocation': DockingLocationFromJSON(json['docking_location']),
    };
}

export function DockingEventSerializerForSpacecraftFlightToJSON(value?: DockingEventSerializerForSpacecraftFlight | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'docking': (value.docking.toISOString()),
        'departure': value.departure === undefined ? undefined : (value.departure === null ? null : value.departure.toISOString()),
    };
}

