/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LauncherConfigDetailSerializerForAgency
 */
export interface LauncherConfigDetailSerializerForAgency {
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    family?: string;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    variant?: string;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    alias?: string;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    minStage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    maxStage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    length?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    diameter?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    maidenFlight?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    launchMass?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    leoCapacity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    gtoCapacity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    toThrust?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    apogee?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    vehicleRange?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    infoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    wikiUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    readonly consecutiveSuccessfulLaunches: number;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    readonly successfulLaunches: number;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    readonly failedLaunches: number;
    /**
     * 
     * @type {number}
     * @memberof LauncherConfigDetailSerializerForAgency
     */
    readonly pendingLaunches: number;
}

export function LauncherConfigDetailSerializerForAgencyFromJSON(json: any): LauncherConfigDetailSerializerForAgency {
    return LauncherConfigDetailSerializerForAgencyFromJSONTyped(json, false);
}

export function LauncherConfigDetailSerializerForAgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LauncherConfigDetailSerializerForAgency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'family': !exists(json, 'family') ? undefined : json['family'],
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'variant': !exists(json, 'variant') ? undefined : json['variant'],
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'minStage': !exists(json, 'min_stage') ? undefined : json['min_stage'],
        'maxStage': !exists(json, 'max_stage') ? undefined : json['max_stage'],
        'length': !exists(json, 'length') ? undefined : json['length'],
        'diameter': !exists(json, 'diameter') ? undefined : json['diameter'],
        'maidenFlight': !exists(json, 'maiden_flight') ? undefined : (json['maiden_flight'] === null ? null : new Date(json['maiden_flight'])),
        'launchMass': !exists(json, 'launch_mass') ? undefined : json['launch_mass'],
        'leoCapacity': !exists(json, 'leo_capacity') ? undefined : json['leo_capacity'],
        'gtoCapacity': !exists(json, 'gto_capacity') ? undefined : json['gto_capacity'],
        'toThrust': !exists(json, 'to_thrust') ? undefined : json['to_thrust'],
        'apogee': !exists(json, 'apogee') ? undefined : json['apogee'],
        'vehicleRange': !exists(json, 'vehicle_range') ? undefined : json['vehicle_range'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
        'infoUrl': !exists(json, 'info_url') ? undefined : json['info_url'],
        'wikiUrl': !exists(json, 'wiki_url') ? undefined : json['wiki_url'],
        'consecutiveSuccessfulLaunches': json['consecutive_successful_launches'],
        'successfulLaunches': json['successful_launches'],
        'failedLaunches': json['failed_launches'],
        'pendingLaunches': json['pending_launches'],
    };
}

export function LauncherConfigDetailSerializerForAgencyToJSON(value?: LauncherConfigDetailSerializerForAgency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'family': value.family,
        'full_name': value.fullName,
        'variant': value.variant,
        'alias': value.alias,
        'min_stage': value.minStage,
        'max_stage': value.maxStage,
        'length': value.length,
        'diameter': value.diameter,
        'maiden_flight': value.maidenFlight === undefined ? undefined : (value.maidenFlight === null ? null : value.maidenFlight.toISOString().substr(0,10)),
        'launch_mass': value.launchMass,
        'leo_capacity': value.leoCapacity,
        'gto_capacity': value.gtoCapacity,
        'to_thrust': value.toThrust,
        'apogee': value.apogee,
        'vehicle_range': value.vehicleRange,
        'image_url': value.imageUrl,
        'info_url': value.infoUrl,
        'wiki_url': value.wikiUrl,
    };
}

