/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LaunchSerializerMini
 */
export interface LaunchSerializerMini {
    /**
     * 
     * @type {string}
     * @memberof LaunchSerializerMini
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof LaunchSerializerMini
     */
    name?: string;
}

export function LaunchSerializerMiniFromJSON(json: any): LaunchSerializerMini {
    return LaunchSerializerMiniFromJSONTyped(json, false);
}

export function LaunchSerializerMiniFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchSerializerMini {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function LaunchSerializerMiniToJSON(value?: LaunchSerializerMini | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

