/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    mapImage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    readonly totalLaunchCount: number;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    readonly totalLandingCount: number;
}

export function LocationFromJSON(json: any): Location {
    return LocationFromJSONTyped(json, false);
}

export function LocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Location {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
        'mapImage': !exists(json, 'map_image') ? undefined : json['map_image'],
        'totalLaunchCount': json['total_launch_count'],
        'totalLandingCount': json['total_landing_count'],
    };
}

export function LocationToJSON(value?: Location | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'country_code': value.countryCode,
        'map_image': value.mapImage,
    };
}

