/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PadSerializerNoLocation,
    PadSerializerNoLocationFromJSON,
    PadSerializerNoLocationFromJSONTyped,
    PadSerializerNoLocationToJSON,
} from './PadSerializerNoLocation';

/**
 * 
 * @export
 * @interface LocationDetail
 */
export interface LocationDetail {
    /**
     * 
     * @type {number}
     * @memberof LocationDetail
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof LocationDetail
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationDetail
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationDetail
     */
    mapImage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LocationDetail
     */
    readonly totalLaunchCount: number;
    /**
     * 
     * @type {number}
     * @memberof LocationDetail
     */
    readonly totalLandingCount: number;
    /**
     * 
     * @type {Array<PadSerializerNoLocation>}
     * @memberof LocationDetail
     */
    pads: Array<PadSerializerNoLocation>;
}

export function LocationDetailFromJSON(json: any): LocationDetail {
    return LocationDetailFromJSONTyped(json, false);
}

export function LocationDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
        'mapImage': !exists(json, 'map_image') ? undefined : json['map_image'],
        'totalLaunchCount': json['total_launch_count'],
        'totalLandingCount': json['total_landing_count'],
        'pads': ((json['pads'] as Array<any>).map(PadSerializerNoLocationFromJSON)),
    };
}

export function LocationDetailToJSON(value?: LocationDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'country_code': value.countryCode,
        'map_image': value.mapImage,
        'pads': ((value.pads as Array<any>).map(PadSerializerNoLocationToJSON)),
    };
}

