/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Orbit,
    OrbitFromJSON,
    OrbitFromJSONTyped,
    OrbitToJSON,
} from './Orbit';

/**
 * 
 * @export
 * @interface Mission
 */
export interface Mission {
    /**
     * 
     * @type {number}
     * @memberof Mission
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Mission
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Mission
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Mission
     */
    launchDesignator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Mission
     */
    readonly type: string;
    /**
     * 
     * @type {Orbit}
     * @memberof Mission
     */
    orbit: Orbit;
}

export function MissionFromJSON(json: any): Mission {
    return MissionFromJSONTyped(json, false);
}

export function MissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'launchDesignator': !exists(json, 'launch_designator') ? undefined : json['launch_designator'],
        'type': json['type'],
        'orbit': OrbitFromJSON(json['orbit']),
    };
}

export function MissionToJSON(value?: Mission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'launch_designator': value.launchDesignator,
        'orbit': OrbitToJSON(value.orbit),
    };
}

