/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpaceStationStatus,
    SpaceStationStatusFromJSON,
    SpaceStationStatusFromJSONTyped,
    SpaceStationStatusToJSON,
} from './SpaceStationStatus';

/**
 * 
 * @export
 * @interface SpaceStationSerializerForCommon
 */
export interface SpaceStationSerializerForCommon {
    /**
     * 
     * @type {number}
     * @memberof SpaceStationSerializerForCommon
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationSerializerForCommon
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationSerializerForCommon
     */
    name: string;
    /**
     * 
     * @type {SpaceStationStatus}
     * @memberof SpaceStationSerializerForCommon
     */
    readonly status: SpaceStationStatus | null;
    /**
     * 
     * @type {Date}
     * @memberof SpaceStationSerializerForCommon
     */
    founded: Date;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationSerializerForCommon
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationSerializerForCommon
     */
    readonly orbit: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationSerializerForCommon
     */
    imageUrl?: string | null;
}

export function SpaceStationSerializerForCommonFromJSON(json: any): SpaceStationSerializerForCommon {
    return SpaceStationSerializerForCommonFromJSONTyped(json, false);
}

export function SpaceStationSerializerForCommonFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceStationSerializerForCommon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'status': SpaceStationStatusFromJSON(json['status']),
        'founded': (new Date(json['founded'])),
        'description': json['description'],
        'orbit': json['orbit'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
    };
}

export function SpaceStationSerializerForCommonToJSON(value?: SpaceStationSerializerForCommon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'founded': (value.founded.toISOString().substr(0,10)),
        'description': value.description,
        'image_url': value.imageUrl,
    };
}

