/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agency,
    AgencyFromJSON,
    AgencyFromJSONTyped,
    AgencyToJSON,
} from './Agency';
import {
    DockingLocationSerializerForSpacestation,
    DockingLocationSerializerForSpacestationFromJSON,
    DockingLocationSerializerForSpacestationFromJSONTyped,
    DockingLocationSerializerForSpacestationToJSON,
} from './DockingLocationSerializerForSpacestation';
import {
    ExpeditionDetailedSerializerForSpacestation,
    ExpeditionDetailedSerializerForSpacestationFromJSON,
    ExpeditionDetailedSerializerForSpacestationFromJSONTyped,
    ExpeditionDetailedSerializerForSpacestationToJSON,
} from './ExpeditionDetailedSerializerForSpacestation';
import {
    SpaceStationStatus,
    SpaceStationStatusFromJSON,
    SpaceStationStatusFromJSONTyped,
    SpaceStationStatusToJSON,
} from './SpaceStationStatus';
import {
    SpaceStationType,
    SpaceStationTypeFromJSON,
    SpaceStationTypeFromJSONTyped,
    SpaceStationTypeToJSON,
} from './SpaceStationType';

/**
 * 
 * @export
 * @interface SpaceStationDetailed
 */
export interface SpaceStationDetailed {
    /**
     * 
     * @type {number}
     * @memberof SpaceStationDetailed
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationDetailed
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationDetailed
     */
    name: string;
    /**
     * 
     * @type {SpaceStationStatus}
     * @memberof SpaceStationDetailed
     */
    readonly status: SpaceStationStatus | null;
    /**
     * 
     * @type {SpaceStationType}
     * @memberof SpaceStationDetailed
     */
    readonly type: SpaceStationType | null;
    /**
     * 
     * @type {Date}
     * @memberof SpaceStationDetailed
     */
    founded: Date;
    /**
     * 
     * @type {Date}
     * @memberof SpaceStationDetailed
     */
    deorbited?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof SpaceStationDetailed
     */
    height?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SpaceStationDetailed
     */
    width?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SpaceStationDetailed
     */
    mass?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SpaceStationDetailed
     */
    volume?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationDetailed
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationDetailed
     */
    readonly orbit: string;
    /**
     * 
     * @type {number}
     * @memberof SpaceStationDetailed
     */
    onboardCrew: number;
    /**
     * 
     * @type {Array<Agency>}
     * @memberof SpaceStationDetailed
     */
    readonly owners: Array<Agency>;
    /**
     * 
     * @type {Array<ExpeditionDetailedSerializerForSpacestation>}
     * @memberof SpaceStationDetailed
     */
    readonly activeExpeditions: Array<ExpeditionDetailedSerializerForSpacestation>;
    /**
     * 
     * @type {Array<DockingLocationSerializerForSpacestation>}
     * @memberof SpaceStationDetailed
     */
    readonly dockingLocation: Array<DockingLocationSerializerForSpacestation>;
    /**
     * 
     * @type {string}
     * @memberof SpaceStationDetailed
     */
    imageUrl?: string | null;
}

export function SpaceStationDetailedFromJSON(json: any): SpaceStationDetailed {
    return SpaceStationDetailedFromJSONTyped(json, false);
}

export function SpaceStationDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceStationDetailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'name': json['name'],
        'status': SpaceStationStatusFromJSON(json['status']),
        'type': SpaceStationTypeFromJSON(json['type']),
        'founded': (new Date(json['founded'])),
        'deorbited': !exists(json, 'deorbited') ? undefined : (json['deorbited'] === null ? null : new Date(json['deorbited'])),
        'height': !exists(json, 'height') ? undefined : json['height'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'mass': !exists(json, 'mass') ? undefined : json['mass'],
        'volume': !exists(json, 'volume') ? undefined : json['volume'],
        'description': json['description'],
        'orbit': json['orbit'],
        'onboardCrew': json['onboard_crew'],
        'owners': ((json['owners'] as Array<any>).map(AgencyFromJSON)),
        'activeExpeditions': ((json['active_expeditions'] as Array<any>).map(ExpeditionDetailedSerializerForSpacestationFromJSON)),
        'dockingLocation': ((json['docking_location'] as Array<any>).map(DockingLocationSerializerForSpacestationFromJSON)),
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
    };
}

export function SpaceStationDetailedToJSON(value?: SpaceStationDetailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'founded': (value.founded.toISOString().substr(0,10)),
        'deorbited': value.deorbited === undefined ? undefined : (value.deorbited === null ? null : value.deorbited.toISOString().substr(0,10)),
        'height': value.height,
        'width': value.width,
        'mass': value.mass,
        'volume': value.volume,
        'description': value.description,
        'onboard_crew': value.onboardCrew,
        'image_url': value.imageUrl,
    };
}

