/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AstronautFlight,
    AstronautFlightFromJSON,
    AstronautFlightFromJSONTyped,
    AstronautFlightToJSON,
} from './AstronautFlight';
import {
    DockingEventSerializerForSpacecraftFlight,
    DockingEventSerializerForSpacecraftFlightFromJSON,
    DockingEventSerializerForSpacecraftFlightFromJSONTyped,
    DockingEventSerializerForSpacecraftFlightToJSON,
} from './DockingEventSerializerForSpacecraftFlight';
import {
    SpacecraftDetailedNoFlights,
    SpacecraftDetailedNoFlightsFromJSON,
    SpacecraftDetailedNoFlightsFromJSONTyped,
    SpacecraftDetailedNoFlightsToJSON,
} from './SpacecraftDetailedNoFlights';

/**
 * 
 * @export
 * @interface SpacecraftFlightDetailedSerializerForLaunch
 */
export interface SpacecraftFlightDetailedSerializerForLaunch {
    /**
     * 
     * @type {number}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    readonly url: string;
    /**
     * 
     * @type {Date}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    missionEnd?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    destination?: string | null;
    /**
     * 
     * @type {Array<AstronautFlight>}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    readonly launchCrew: Array<AstronautFlight>;
    /**
     * 
     * @type {Array<AstronautFlight>}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    readonly onboardCrew: Array<AstronautFlight>;
    /**
     * 
     * @type {Array<AstronautFlight>}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    readonly landingCrew: Array<AstronautFlight>;
    /**
     * 
     * @type {SpacecraftDetailedNoFlights}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    readonly spacecraft: SpacecraftDetailedNoFlights | null;
    /**
     * 
     * @type {Array<DockingEventSerializerForSpacecraftFlight>}
     * @memberof SpacecraftFlightDetailedSerializerForLaunch
     */
    readonly dockingEvents: Array<DockingEventSerializerForSpacecraftFlight>;
}

export function SpacecraftFlightDetailedSerializerForLaunchFromJSON(json: any): SpacecraftFlightDetailedSerializerForLaunch {
    return SpacecraftFlightDetailedSerializerForLaunchFromJSONTyped(json, false);
}

export function SpacecraftFlightDetailedSerializerForLaunchFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacecraftFlightDetailedSerializerForLaunch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'missionEnd': !exists(json, 'mission_end') ? undefined : (json['mission_end'] === null ? null : new Date(json['mission_end'])),
        'destination': !exists(json, 'destination') ? undefined : json['destination'],
        'launchCrew': ((json['launch_crew'] as Array<any>).map(AstronautFlightFromJSON)),
        'onboardCrew': ((json['onboard_crew'] as Array<any>).map(AstronautFlightFromJSON)),
        'landingCrew': ((json['landing_crew'] as Array<any>).map(AstronautFlightFromJSON)),
        'spacecraft': SpacecraftDetailedNoFlightsFromJSON(json['spacecraft']),
        'dockingEvents': ((json['docking_events'] as Array<any>).map(DockingEventSerializerForSpacecraftFlightFromJSON)),
    };
}

export function SpacecraftFlightDetailedSerializerForLaunchToJSON(value?: SpacecraftFlightDetailedSerializerForLaunch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'mission_end': value.missionEnd === undefined ? undefined : (value.missionEnd === null ? null : value.missionEnd.toISOString()),
        'destination': value.destination,
    };
}

