/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events. 

While this API is free to use it is subject to rate limiting for non-authenticated requests.

Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.

If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 * OpenAPI spec version: v2.2.0
 */

export type AstronautListParams = {
  agency__abbrev?: string;
  agency__name?: string;
  date_of_birth?: string;
  date_of_birth__gt?: string;
  date_of_birth__gte?: string;
  date_of_birth__lt?: string;
  date_of_birth__lte?: string;
  date_of_death?: string;
  date_of_death__gt?: string;
  date_of_death__gte?: string;
  date_of_death__lt?: string;
  date_of_death__lte?: string;
  limit?: number;
  name?: string;
  nationality?: string;
  offset?: number;
  ordering?: string;
  search?: string;
  status?: number;
};
