/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events. 

While this API is free to use it is subject to rate limiting for non-authenticated requests.

Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.

If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 * OpenAPI spec version: v2.2.0
 */
import type { AstronautType } from "./astronautType";
import type { AstronautStatus } from "./astronautStatus";
import type { AgencySerializerMini } from "./agencySerializerMini";

export interface AstronautDetailedSerializerNoFlights {
  readonly id: number;
  readonly url: string;
  name: string;
  readonly type: AstronautType;
  readonly status: AstronautStatus;
  readonly agency: AgencySerializerMini;
  date_of_birth?: string | null;
  date_of_death?: string | null;
  nationality: string;
  twitter?: string | null;
  instagram?: string | null;
  bio: string;
  profile_image?: string | null;
  wiki?: string | null;
  readonly last_flight: string;
  readonly first_flight: string;
}
