/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events. 

While this API is free to use it is subject to rate limiting for non-authenticated requests.

Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.

If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 * OpenAPI spec version: v2.2.0
 */

export type ExpeditionListParams = {
  crew__astronaut?: number;
  crew__astronaut__agency?: number;
  end__gt?: string;
  end__gte?: string;
  end__lt?: string;
  end__lte?: string;
  limit?: number;
  name?: string;
  offset?: number;
  ordering?: string;
  search?: string;
  space_station?: number;
  start__gt?: string;
  start__gte?: string;
  start__lt?: string;
  start__lte?: string;
};
