/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events. 

While this API is free to use it is subject to rate limiting for non-authenticated requests.

Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.

If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 * OpenAPI spec version: v2.2.0
 */
import type { LauncherDetailed } from './launcherDetailed';
import type { Landing } from './landing';
import type { LaunchSerializerMini } from './launchSerializerMini';

export interface FirstStage {
  readonly id: number;
  readonly type: string;
  reused?: boolean | null;
  readonly launcher_flight_number: number;
  readonly launcher: LauncherDetailed;
  readonly landing: Landing;
  readonly previous_flight_date: string;
  readonly turn_around_time_days: number;
  readonly previous_flight: LaunchSerializerMini;
}
