/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events. 

While this API is free to use it is subject to rate limiting for non-authenticated requests.

Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.

If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 * OpenAPI spec version: v2.2.0
 */

export interface LauncherConfigDetailSerializerForAgency {
  readonly id: number;
  readonly url: string;
  name: string;
  description?: string;
  family?: string;
  full_name?: string;
  variant?: string;
  alias?: string;
  min_stage?: number | null;
  max_stage?: number | null;
  length?: number | null;
  diameter?: number | null;
  maiden_flight?: string | null;
  launch_mass?: number | null;
  leo_capacity?: number | null;
  gto_capacity?: number | null;
  to_thrust?: number | null;
  apogee?: number | null;
  vehicle_range?: number | null;
  image_url?: string | null;
  info_url?: string | null;
  wiki_url?: string | null;
  readonly consecutive_successful_launches: number;
  readonly successful_launches: number;
  readonly failed_launches: number;
  readonly pending_launches: number;
}
