/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events. 

While this API is free to use it is subject to rate limiting for non-authenticated requests.

Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.

If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 * OpenAPI spec version: v2.2.0
 */
import type { AgencySerializerMini } from "./agencySerializerMini";
import type { MissionPatch } from "./missionPatch";

export interface Program {
  readonly id: number;
  readonly url: string;
  name: string;
  description?: string | null;
  readonly agencies: AgencySerializerMini[];
  image_url: string;
  start_date?: string | null;
  end_date?: string | null;
  info_url?: string | null;
  wiki_url?: string | null;
  readonly mission_patches: MissionPatch[];
}
