image:
  repository: registry.digitalocean.com/spacelaunchnow-registry/sln-ui
  tag: production
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  normal: {}
  web: {}

secret: {}

web:
  replicaCount: 1
  port: 80
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  budget:
    minAvailable: 1 # Ignored when replicaCount is 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  livenessProbe:
    failureThreshold: 10
    initialDelaySeconds: 10
    timeoutSeconds: 10
    path: "/"
    port: 80
  readinessProbe:
    failureThreshold: 10
    initialDelaySeconds: 10
    timeoutSeconds: 10
    path: "/"
    port: 80
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: dev-ui.spacelaunchnow.me
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: spacelaunchnow-tls
        hosts:
          - dev-ui.spacelaunchnow.me

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
