/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    LauncherDetail,
    LauncherDetailFromJSON,
    LauncherDetailToJSON,
    PaginatedLauncherList,
    PaginatedLauncherListFromJSON,
    PaginatedLauncherListToJSON,
} from '../models';

export interface LauncherListRequest {
    flightProven?: boolean;
    id?: number;
    launcherConfig?: number;
    launcherConfigManufacturer?: number;
    limit?: number;
    offset?: number;
    ordering?: string;
    search?: string;
    serialNumber?: string;
}

export interface LauncherRetrieveRequest {
    id: number;
}

/**
 * 
 */
export class LauncherApi extends runtime.BaseAPI {

    /**
     * API endpoint that allows Launcher instances to be viewed.  GET: Return a list of all the existing launcher instances.  FILTERS: Parameters - \'id\', \'serial_number\', \'flight_proven\', \'launcher_config\', \'launcher_config__manufacturer\' Example - /2.2.0/launcher/?serial_number=B1046  SEARCH EXAMPLE: /2.2.0/launcher/?search=expended Searches through serial number or status  ORDERING: Fields - \'id\', \'flight_proven\', Example - /2.2.0/launcher/?order=flight_proven
     */
    async launcherListRaw(requestParameters: LauncherListRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PaginatedLauncherList>> {
        const queryParameters: any = {};

        if (requestParameters.flightProven !== undefined) {
            queryParameters['flight_proven'] = requestParameters.flightProven;
        }

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.launcherConfig !== undefined) {
            queryParameters['launcher_config'] = requestParameters.launcherConfig;
        }

        if (requestParameters.launcherConfigManufacturer !== undefined) {
            queryParameters['launcher_config__manufacturer'] = requestParameters.launcherConfigManufacturer;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.ordering !== undefined) {
            queryParameters['ordering'] = requestParameters.ordering;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.serialNumber !== undefined) {
            queryParameters['serial_number'] = requestParameters.serialNumber;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/2.2.0/launcher/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLauncherListFromJSON(jsonValue));
    }

    /**
     * API endpoint that allows Launcher instances to be viewed.  GET: Return a list of all the existing launcher instances.  FILTERS: Parameters - \'id\', \'serial_number\', \'flight_proven\', \'launcher_config\', \'launcher_config__manufacturer\' Example - /2.2.0/launcher/?serial_number=B1046  SEARCH EXAMPLE: /2.2.0/launcher/?search=expended Searches through serial number or status  ORDERING: Fields - \'id\', \'flight_proven\', Example - /2.2.0/launcher/?order=flight_proven
     */
    async launcherList(requestParameters: LauncherListRequest = {}, initOverrides?: RequestInit): Promise<PaginatedLauncherList> {
        const response = await this.launcherListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint that allows Launcher instances to be viewed.  GET: Return a list of all the existing launcher instances.  FILTERS: Parameters - \'id\', \'serial_number\', \'flight_proven\', \'launcher_config\', \'launcher_config__manufacturer\' Example - /2.2.0/launcher/?serial_number=B1046  SEARCH EXAMPLE: /2.2.0/launcher/?search=expended Searches through serial number or status  ORDERING: Fields - \'id\', \'flight_proven\', Example - /2.2.0/launcher/?order=flight_proven
     */
    async launcherRetrieveRaw(requestParameters: LauncherRetrieveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<LauncherDetail>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling launcherRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/2.2.0/launcher/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LauncherDetailFromJSON(jsonValue));
    }

    /**
     * API endpoint that allows Launcher instances to be viewed.  GET: Return a list of all the existing launcher instances.  FILTERS: Parameters - \'id\', \'serial_number\', \'flight_proven\', \'launcher_config\', \'launcher_config__manufacturer\' Example - /2.2.0/launcher/?serial_number=B1046  SEARCH EXAMPLE: /2.2.0/launcher/?search=expended Searches through serial number or status  ORDERING: Fields - \'id\', \'flight_proven\', Example - /2.2.0/launcher/?order=flight_proven
     */
    async launcherRetrieve(requestParameters: LauncherRetrieveRequest, initOverrides?: RequestInit): Promise<LauncherDetail> {
        const response = await this.launcherRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
