/* tslint:disable */
/* eslint-disable */
/**
 * Launch Library
 * The Launch Library API is a product by The Space Devs with an up-to-date database of Spaceflight events.   While this API is free to use it is subject to rate limiting for non-authenticated requests.  Please use https://lldev.thespacedevs.com for development testing - the development endpoint has stale data but is not subject to any rate limits.  If you are interested in a higher rate limit please consider supporting the project on Patreon for access to an API Key.
 *
 * The version of the OpenAPI document: v2.2.0
 * Contact: support@thespacedevs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Pad,
    PadFromJSON,
    PadToJSON,
    PaginatedPadList,
    PaginatedPadListFromJSON,
    PaginatedPadListToJSON,
} from '../models';

export interface PadListRequest {
    id?: number;
    limit?: number;
    location?: number;
    name?: string;
    offset?: number;
    search?: string;
}

export interface PadRetrieveRequest {
    id: number;
}

/**
 * 
 */
export class PadApi extends runtime.BaseAPI {

    /**
     * API endpoint that allows Location instances to be viewed.  GET: Return a list of all the existing location instances.  FILTERS: Parameters - \'name\', \'location\' Example - /2.2.0/pad/?location=12
     */
    async padListRaw(requestParameters: PadListRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PaginatedPadList>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.location !== undefined) {
            queryParameters['location'] = requestParameters.location;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/2.2.0/pad/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedPadListFromJSON(jsonValue));
    }

    /**
     * API endpoint that allows Location instances to be viewed.  GET: Return a list of all the existing location instances.  FILTERS: Parameters - \'name\', \'location\' Example - /2.2.0/pad/?location=12
     */
    async padList(requestParameters: PadListRequest = {}, initOverrides?: RequestInit): Promise<PaginatedPadList> {
        const response = await this.padListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API endpoint that allows Location instances to be viewed.  GET: Return a list of all the existing location instances.  FILTERS: Parameters - \'name\', \'location\' Example - /2.2.0/pad/?location=12
     */
    async padRetrieveRaw(requestParameters: PadRetrieveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Pad>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling padRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/2.2.0/pad/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PadFromJSON(jsonValue));
    }

    /**
     * API endpoint that allows Location instances to be viewed.  GET: Return a list of all the existing location instances.  FILTERS: Parameters - \'name\', \'location\' Example - /2.2.0/pad/?location=12
     */
    async padRetrieve(requestParameters: PadRetrieveRequest, initOverrides?: RequestInit): Promise<Pad> {
        const response = await this.padRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
