apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}